site_name: NKR Documentation
site_description: User documentation for NKR - Bois
site_url: https://techlib.github.io/NKR-docs/
repo_url: https://github.com/techlib/NKR-docs
repo_name: techlib/NKR-docs

theme:
  name: material
  language: en
  palette:
    scheme: default
    primary: red

nav:
  - Introduction: index.md
  - Login: login.md
  - Menu: menu.md
